projects:
  loopLog:
    directories:
      - /Users/checkito/workspace/it-training/loop/var/log
    log_pattern: "logstash-*.json"
    position_storage:
      type: file
      path: var/positions
  
  checkout:
    directories:
      - /Users/checkito/workspace/checkout1/data/log
    log_pattern: "logstash-*.json"
    position_storage:
      type: file
      path: var/positions 