projects:
  loopLog:
    directories:
      - /var/log
    log_pattern: "logstash-*.json"
  
  checkout:
    directories:
      - /Users/checkito/workspace/checkout1/data/log
    log_pattern: "logstash-*.json"
