# Example configuration for Log Monitor
# Copy this file to config/projects.yaml and modify for your projects

projects:
  # Example project: MyApp
  myapp:
    directories:
      - /var/log/myapp
      - /opt/myapp/logs
    log_pattern: "logstash-*.json"
    position_storage:
      type: cached
      path: var/positions
      save_interval_seconds: 30
  
  # Example project: API Service
  api:
    directories:
      - /var/log/api
      - /var/log/api/errors
    log_pattern: "api-*.json"
    position_storage:
      type: cached
      path: var/positions
      save_interval_seconds: 30
  
  # Example project: Web Application
  webapp:
    directories:
      - /var/log/webapp
    log_pattern: "webapp-*.log"
    position_storage:
      type: file
      path: var/positions
  
  # Example project: Database Logs
  database:
    directories:
      - /var/log/mysql
      - /var/log/postgresql
    log_pattern: "*.log"
    position_storage:
      type: async
      path: var/positions
      save_interval_seconds: 60

# Configuration Options:
#
# directories: List of directories to monitor for log files
# log_pattern: Glob pattern to match log files (e.g., "*.json", "logstash-*.json")
# position_storage:
#   type: "file" | "cached" | "async" - Storage backend for file positions
#   path: Directory to store position files
#   save_interval_seconds: How often to save positions (for cached/async types)
#
# Position Storage Types:
# - file: Simple file-based storage, saves immediately
# - cached: In-memory cache with periodic saves
# - async: Asynchronous saves for high-performance scenarios 