projects:
  loopLog:
    directories:
      - /Users/checkito/workspace/it-training/loop/var/log
    log_pattern: "logstash-*.json"
  
  checkout:
    directories:
      - /Users/checkito/workspace/checkout1/data/log
    log_pattern: "logstash-*.json"
