name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [8.3]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: pcntl
        coverage: xdebug
        tools: composer:v2
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    
    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Create necessary directories
      run: |
        mkdir -p var/log
        mkdir -p var/positions
        mkdir -p var/.phpunit.cache
    
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --memory-limit=2G
    
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --coverage-text --coverage-filter=src
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          var/log/junit.xml
          var/log/testdox.html
          var/log/testdox.txt
        retention-days: 30 